name = "uml_model"
description = "Language-neutral UML model types"
version = "0.1.0-dev"
licenses = "BSD-3-Clause"
authors = ["Joe Beazelman"]
maintainers = ["Joe Beazelman <joe@example.com>"]
maintainers-logins = ["Joebeazelman"]
website = "https://github.com/Joebeazelman/uml_model"
tags = ["uml", "model", "code-generation"]

[[depends-on]]
aunit = "*"
string_utilities = "*"

[[actions]]
type = "test"
command = ["sh", "-c", "alr exec -- gprbuild -P tests/uml_model_tests.gpr -p && ./tests/obj/tests"]

[[pins]]
string_utilities = { path='../string_utilities' }